name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/ci-cd.yml"

  workflow_dispatch:

jobs:
  docker:
    name: Build and publish frontend
    uses: nesco-devops/Action3/.github/workflows/docker-build-push.yml@main

    with:
      image_name: appgestion-frontend
      build_context: ./frontend
      dockerfile: ./frontend/Dockerfile
      gitops_manifest: frontend/deployment.yaml

    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
